#!/bin/sh -e

echo "Library Path: $LIBVERTO" >&2
echo -n "Hash Command: "
if which md5sum 2>/dev/null; then
  HASHCMD="md5sum"
elif which md5; then
  HASHCMD="md5"
else
  echo "ERROR!"
  exit 1
fi

HASH=`nm -g $LIBVERTO | awk '/^[0-9a-fA-F]+ T verto_/ { print $NF; }' | sed 's|^_||' | sort -u | $HASHCMD | cut -d' ' -f1`
echo "Hash: $HASH"
test $HASH = 9f533c441fe590ad19c454db896a8673
